# Generated by Django 5.1.6 on 2025-02-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_seller_product_status_alter_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('ETB', 'Ethiopian Birr'), ('USD', 'US Dollar'), ('AED', 'UAE Dirham')], default='ETB', max_length=3),
        ),
    ]
