# Generated by Django 5.1.6 on 2025-02-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20250227_1212'),
    ]

    operations = [
    ]
