# Generated by Django 5.1.6 on 2025-03-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20250227_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('ETB', 'Ethiopian Birr'), ('USD', 'US Dollar'), ('AED', 'UAE Dirham')], default='ETB', max_length=3),
        ),
    ]
